### ISSUE TITLE
Damage Frequently Calculating Incorrectly

### ISSUE THREAD

**Issue by Polygamoose** [Vendare/DarkHeresy2E-FoundryVTT#153]
I cannot for the life of me figure out why it's doing this, but the damage frequently gets calculated incorrectly.
To test this, I made a brand new character, did nothing to him but give him a Lasgun (1d10+3 damage) and 100 Ballistic Skill, and rolled a test.

First test I rolled, rolled a 2, and chat says I dealt 6 damage... but 2 + 3 = 5.
I rolled a couple dozen more times and figured out that it cannot roll less than 9 damage total.
Roll a 1? 1 + 3 = 9
Roll a 3? 3 + 3 = 9

So on and so forth. 
Roll a 7? 7 + 3 = 10.
8 is 11
9 is 12
10 is 13

I recoded the lasgun to 1d10+10 damage. First roll was a 5, and chat told me I dealt 21 damage even though 10 + 5 = 15.

**Comment by Polygamoose** [comment]
Is there any way we can get this damage issue corrected? It's a major hindrance to gameplay, having to manually check damage every time. And I'm not good enough at coding to pour through the lines of data to figure out what's going wrong, myself.
![image](https://github.com/Vendare/DarkHeresy2E-FoundryVTT/assets/35110805/feae915f-1d2b-4027-b073-baea5a2c2037)

**Comment by StealthBow** [comment]
I'd imagine what you're running into here is that per the Core Rulebook (page 227, second paragraph of "Step Four"), you can replace a single damage die result with the Degrees of Success on the attack roll. The system is built to work with this part of the rules automatically.

> ![image](https://private-user-images.githubusercontent.com/35110805/299565236-feae915f-1d2b-4027-b073-baea5a2c2037.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTA2MjQsIm5iZiI6MTcwNjQ5MDMyNCwicGF0aCI6Ii8zNTExMDgwNS8yOTk1NjUyMzYtZmVhZTkxNWYtMWQyYi00MDI3LWIwNzMtYmFlYTVhMmMyMDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAxMDUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZGI1ZmRjZDcwNTZjNjYwOGUyMGQxOWY0YzkyY2U1ZTIxZTM3NjJkOTI3MTZiM2E0Yzg1MGU4Nzc2YTQ3ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MdmHJ3KbxkZ8zmi9-dEGTFPXUTVGx7p-A0SPxwkleNs)

In this screenshot I'd guess you had 5 Degrees of Success on the attack roll so the 2 on the die was replaced (5+0 for 5 total)


> ![image](https://private-user-images.githubusercontent.com/35110805/299567075-85f37cdd-0f29-4717-89dd-6ebd6dd47fef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTA2MjQsIm5iZiI6MTcwNjQ5MDMyNCwicGF0aCI6Ii8zNTExMDgwNS8yOTk1NjcwNzUtODVmMzdjZGQtMGYyOS00NzE3LTg5ZGQtNmViZDZkZDQ3ZmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAxMDUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NTljZjE0MTRlZmI2NjZmMzY3M2FkM2VlZTIyYzA1YmE3MjI4YzA4ZjFhNjgzYTVjNzMwYTI4YTdmM2EyZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CJ4Infous5dBCBm6rX7bo547_Rsa_-PPoanorFk_BnE)

And in this I'd guess you had 8 Degrees of Success on the attack roll so the 3 on the die was replaced (8+3 for 11 total).

A further example that I've just thrown together:
![DH2e_Test](https://github.com/Vendare/DarkHeresy2E-FoundryVTT/assets/1633044/6958f6f1-3689-4c6d-bcc0-0a6bba32b682)
Even though I rolled a 10 on the damage die, because I had 13 Degrees of Success I dealt 13 damage.

**Comment by Vendare** [comment]
As Stealthbow pointed out the system automatically replaces the lowest rolled die on the damage roll with the degrees of success. The damage is calculated correctly
