### ISSUE TITLE
Fate Reroll unavailable for some rolls, available for "non-player owned" rolls

### ISSUE THREAD

**Issue by Vylkire** [Vendare/DarkHeresy2E-FoundryVTT#166]
Fate Reroll context menu appears for player rolls prior to "1 day ago", but not for rolls "today";
![Screenshot from 2024-07-08 15-12-11](https://github.com/Vendare/DarkHeresy2E-FoundryVTT/assets/13192559/7c3dd5b5-ff22-42a2-977c-d46975db6c33)

![Screenshot from 2024-07-08 15-13-00](https://github.com/Vendare/DarkHeresy2E-FoundryVTT/assets/13192559/76e66a37-b7e2-4047-82a6-06eb518696ff)

Additionally, I am able to fate reroll for rolls I did not make;
![Screenshot from 2024-07-08 15-10-14](https://github.com/Vendare/DarkHeresy2E-FoundryVTT/assets/13192559/28a31a31-20b3-48f6-b2cb-d672653b5da3)

This appears to be an issue for players, but also the GM is unable to fate reroll anything from "today". The exact cutoff is unknown as we only noticed it during play, then came back to investigate the next day. I have no idea what's causing it, so I apologise for the lack of information!

**Comment by Vendare** [comment]
The cause for this issue is how foundry handles detecting if a chatmessage constitutes a roll. Pre V12 this was determined by a constant. With the V12 changes this Constant was deprecated and thus i the refence to it removed from the system. The Actual dice rolls for the message where not added to the correct variable so for purposes of adding the option to reroll no chatmessage ever represented a dice roll.
