### ISSUE TITLE
Weapon Special properties readable

### ISSUE THREAD

**Issue by saif-ellafi** [Vendare/DarkHeresy2E-FoundryVTT#18]
The Special properties of Weapons (i.e. Tearing) contain special rules and information.
Right now, in the weapon items this is just a String.
It would be fantastic if we could store the Weapon Properties somehow?

![image](https://user-images.githubusercontent.com/27952699/103480397-62bea980-4dd4-11eb-87b3-e0d265d21b4c.png)

**Comment by aSemy** [comment]
For context: there's about 40 different weapon qualities. The qualities affect lots of things: chance to hit, damage, adding status affects to wounded targets, or even destroying target's equipment. Players might want to add custom ones. There is some overlap with Weapon Modifications as they can affect weapons in the same way.

As it's a text field you could just enter "Tearing (extra dice for damage, drop lowest) CB pg150", and manually change the damage formula. There's a huge amount of room for improvement though.

Improvements I think could be done:

1. When the 'damage roll' message is sent to change, also show the 'Special' text so that players can see and adjust the default roll and apply any custom affects.
2. As there are so many qualities, manual data entry gets very tedious. It would be amazing to be able to have a compendium of Weapon Qualities that can be dragged and dropped onto weapons. I've asked in Discord and this is technically possible but would require custom work to enable drag-and-drop and allow Items to have sub-Items. 

Mechanically, adjusting the hit/damage calculations and statuses based on Qualities is a lot of work. I'm not clear how this could be made generic enough without having spaghetti code that is too rigid.

**Comment by saif-ellafi** [comment]
> For context: there's about 40 different weapon qualities. The qualities affect lots of things: chance to hit, damage, adding status affects to wounded targets, or even destroying target's equipment. Players might want to add custom ones. There is some overlap with Weapon Modifications as they can affect weapons in the same way.
> 
> As it's a text field you could just enter "Tearing (extra dice for damage, drop lowest) CB pg150", and manually change the damage formula. There's a huge amount of room for improvement though.
> 
> Improvements I think could be done:
> 
> 1. When the 'damage roll' message is sent to change, also show the 'Special' text so that players can see and adjust the default roll and apply any custom affects.
> 2. As there are so many qualities, manual data entry gets very tedious. It would be amazing to be able to have a compendium of Weapon Qualities that can be dragged and dropped onto weapons. I've asked in Discord and this is technically possible but would require custom work to enable drag-and-drop and allow Items to have sub-Items.
> 
> Mechanically, adjusting the hit/damage calculations and statuses based on Qualities is a lot of work. I'm not clear how this could be made generic enough without having spaghetti code that is too rigid.

I wasn't thinking on making them apply automatically modifiers, I am actually a non-automation person myself.
What I found missing is a way to quickly find the rules or the meaning of the weapon properties, without having to resort to the book.

As you said perhaps making them Weapon Mods as it is now althought they would be untied to the weapons they are assigned to, the same for mods.

All three, Ammo, Mods and Special attributes are by-weapon so perhaps all 3 could be tied somehow

**Comment by luminousgrue** [comment]
Automating weapon special qualities is plainly unfeasable, but what is feasable is expanding the size of the "Special" field to make weapons with multiple qualities more readable - especially if the intent is to use that field to store instructions to the user for how to hand adjust the hit and damage output.

That last part would also be much easier if the attack function showed us what the actual roll on the damage dice was before modifiers, and easier still if there were a way to just roll damage without having to roll and succeed with DoS on an attack action.

**Comment by Vendare** [comment]
Vengeful, Proven, Primitive, Razor Sharp, Spray and Tearing have been automated.
Weapon Traits as items is to big of a change to implement in the systems lifecycle and will not be done.
