### ISSUE TITLE
Limited permissions still show the entire sheet

### ISSUE THREAD

**Issue by saif-ellafi** [Vendare/DarkHeresy2E-FoundryVTT#8]
When an Actor is on permission "Observer" he can still see the stats, gear, etc.
EDIT: I meant **Limited**

**Comment by moo-man** [comment]
This is typically the intention of observer

**Comment by saif-ellafi** [comment]
Sorry, I meant Limited! Isn't it supposed to show only Bio?

**Comment by moo-man** [comment]
Ah, yeah, well, it can show whatever we want, but it should certainly hide aspects like that.

**Comment by saif-ellafi** [comment]
Yeah, imho it should only show the **Notes** Tab

**Comment by aSemy** [comment]
So there are three levels of permissions players can have on a character. Owner (can see and edit everything), Observer (can see everything, but edit nothing), Limited (???), and None (token is visible but char-sheet is not).

It's not really clear to me what the use case for Limited is.

In the DnD5e module, Limited means the player can see the Name and Notes. This seems a bit strange to me, because as a GM I'd use the Notes for private notes about an NPC that I wouldn't want players to see.

I think that Limited should be defined as 'what the players can physically see, and assumes they have met this person before'. Therefore the character's name and name of any equipped equipment should visible (we don't have an option to mark equipment as equipped like DnD5e... but we should). Maybe the character's Background and Notes>Bio? But not Notes.

**Comment by moo-man** [comment]
I think the convention established by dnd should be maintained, the journal can get cluttered, and the consolidation of notes with the actual actor I think is useful

**Comment by saif-ellafi** [comment]
This is also the reason most people use the module **GM Notes** to store GM specific secrets and notes. The "character notes" may be public if limited visibility is available.

**Comment by moo-man** [comment]
Most people use GM Notes I imagine for Owned Items, as it's a bit redundant for actors, which aren't generally owned by players, except for their personal one.

**Comment by aSemy** [comment]
Alright, let's stick with what dnd5e have done then. Name and Notes only.

**Comment by Vendare** [comment]
Has been implemented
